name: Flutter-Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.9'
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - uses: actions/upload-artifact@master
        with:
          name: app-armeabi-v7a-release
          path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk
      - uses: actions/upload-artifact@master
        with:
          name: app-arm64-v8a-release
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk
      - uses: actions/upload-artifact@master
        with:
          name: app-x86_64-release
          path: build/app/outputs/apk/release/app-x86_64-release.apk
